/**
 * sorcery-registry lookups.
 *
 * Upstream slugs are mutable — the set renumbering rewrote every one of them —
 * so the registry assigns a permanent id per card (codex) and per printing.
 * Import resolution keys on those ids and treats slugs as a fallback.
 *
 * Data is vendored under data/registry and regenerated by
 * scripts/registry/sync-registry.js.
 */
import printingIndex from "../../../data/registry/printing-index.json";

interface PrintingIndex {
  registrySha256: string;
  /** Current and historical upstream slugs (`001-detonate-b-s`) */
  bySlug: Record<string, string>;
  /** Our legacy 3-letter slugs (`alp-detonate-b-s`) */
  byLegacySlug: Record<string, string>;
  codexByPrinting: Record<string, string>;
}

const index = printingIndex as unknown as PrintingIndex;

/** Resolve a printing id from an upstream or legacy slug, in either separator style */
export function printingIdForSlug(slug: string | undefined): string | null {
  if (!slug) return null;
  const normalized = slug.trim().toLowerCase();
  return (
    index.bySlug[normalized] ??
    index.byLegacySlug[normalized] ??
    // Callers hand us both `001-detonate-b-s` and `001_detonate_b_s`
    index.bySlug[normalized.replace(/_/g, "-")] ??
    index.byLegacySlug[normalized.replace(/_/g, "-")] ??
    null
  );
}

/** The card a printing belongs to, for finding other printings of the same card */
export function codexIdForPrinting(printingId: string | undefined): string | null {
  if (!printingId) return null;
  return index.codexByPrinting[printingId] ?? null;
}

/** Checksum of the registry export these lookups were generated from */
export function registryVersion(): string {
  return index.registrySha256;
}
