import { BOARD_PING_LIFETIME_MS, BOARD_PING_MAX_HISTORY, MAX_EVENTS, REMOTE_CURSOR_TTL_MS } from "./types";

export { BOARD_PING_LIFETIME_MS, BOARD_PING_MAX_HISTORY, MAX_EVENTS, REMOTE_CURSOR_TTL_MS };
